fix pipeline 2

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,18 +7,6 @@ on:
   workflow_dispatch:
 
 jobs:
-  validate_files:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Check if tsconfig.json exists
-        run: |
-          if [ ! -f tsconfig.json ]; then
-            echo "🚨 ERROR: tsconfig.json is missing. It is required for the build process."
-            exit 1
-          fi
-        shell: bash
-
   build_and_release:
     runs-on: ubuntu-latest
     needs: validate_files  
@@ -27,10 +15,20 @@ jobs:
       NODE_VERSION: 18
 
     steps:
-      # Configurar a versão do Node.js
+      # Checkout do código
       - name: Checkout code
         uses: actions/checkout@v3
 
+      # Check tsconfig  
+      - name: Check if tsconfig.json exists
+        run: |
+          if [ ! -f tsconfig.json ]; then
+            echo "🚨 ERROR: teste.json is missing. It is required for the build process."
+            exit 1
+          fi
+        shell: bash
+
+      # Configurar a versão do Node.js
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
